name: Auto Run ISO Task
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  run-iso-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Run process
        run: |
          chmod +x build_iso.sh
          ./build_iso.sh
