
name: Auto Run ISO Task
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install QEMU
        run: sudo apt-get update && sudo apt-get install -y qemu-system-x86

      - name: Start VM in Background
        run: |
          # Lancement de la VM avec redirection : 
          # Le port 2222 de l'Action pointera vers le port 22 (SSH) de votre VM.
          qemu-system-x86_64 -m 1024 -cdrom custom-slowdns.iso -nographic -net user,hostfwd=tcp::2222-:22 -net nic &
          sleep 20 # Temps pour laisser la VM démarrer complètement

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: false
